language: node_js
node_js:
  - "12"
cache: npm
install:
  - npm install
script:
  - npm test
env:
  - SENTENCECASE=off CASEPROTECTION=off
  - SENTENCECASE=off CASEPROTECTION=strict
  - SENTENCECASE=off CASEPROTECTION=as-needed
  - SENTENCECASE=on CASEPROTECTION=off
  - SENTENCECASE=on CASEPROTECTION=strict
  - SENTENCECASE=on CASEPROTECTION=as-needed
  - SENTENCECASE=on+guess CASEPROTECTION=off
  - SENTENCECASE=on+guess CASEPROTECTION=strict
  - SENTENCECASE=on+guess CASEPROTECTION=as-needed
