language: node_js
node_js:
- '12'
cache: npm
env:
- SENTENCECASE=off CASEPROTECTION=off
- SENTENCECASE=off CASEPROTECTION=strict
- SENTENCECASE=off CASEPROTECTION=as-needed
- SENTENCECASE=on CASEPROTECTION=off
- SENTENCECASE=on CASEPROTECTION=strict
- SENTENCECASE=on CASEPROTECTION=as-needed
- SENTENCECASE=on+guess CASEPROTECTION=off
- SENTENCECASE=on+guess CASEPROTECTION=strict
- SENTENCECASE=on+guess CASEPROTECTION=as-needed

script:
  - npm test

stages:
  - test
  - release

jobs:
  include:
  - stage: release
    if: tag IS present
    script:
    - npm start
    deploy:
      on:
        tags: true
        branch: master
      provider: npm
      edge: true
      email: emiliano.heyns@iris-advies.com
      api_key:
        secure: bdx08YcwgenNCtWbaWrF9HPUHNCGP5RKlrOq5ri21+cYl1JVyzgavNxqyrJKwSYtjMkUIxnzGvLGi20wlNDU+SV+mpQik5/usjwwpnlNYCDuZvJHC7TtTl8s9rivp990bKCNggztu+7wkzJ3ojtA7GLlID1dqt/cvWk1s1sNNHXQDYGrFu0NWoNgi4OFJo4wgL4w8NsDzx+YJa8EGv/MkRsZ0Z1uv/fJTFXueNlDkm4l3solv6tidNgNtLojSYo7w7xCQIFIPqCNpDhN9tOHnjwUdAQu0CCw1G/smdLTmD5uaszFpbTCEd+TCPusC104mIN1zH+mmTxSU9pQDpHuVTqKcqL6Qv29DMtPfJC8ESkEVsojmO7dNluEpA/7LdWj/sf5QSybegOjFDE3M1o9y5dBcuvbPKWxw6Rg4CwF57hGbJaHXGxq47SL8TMmKICuQftBHTHWSmncHJ8csfDvHcBMT0VkuBTHs81aZ3i0QDwIAcXTAEx3zjg+F+M3V9WnAXaxX+ZKw/7ltlIenFPaA6PptLmPMtrL1WVg/TPavVSMNHw0MgzEx//WlXYPBjh2XDelfjRWyEEfSypls6k924gtM1fj3NwdgB6g92UxrCSADIV+6ipltq42+13dfhs21UAjiA6BKGx5PcbKyXiZM4Vto9gfiAFfEEag5+sRVpE=
