name: test & publish

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sentencecase: [ 'off', 'on', 'on+guess' ]
        caseprotection: [ 'off', 'strict', 'as-needed' ]
    steps:
    - uses: actions/checkout@v2
    - run: echo "::set-output name=version::"`jq -r .version package.json`
      id: version
    - run: echo "::set-output name=bogus::true"
      id: bogus
      if: github.event.head_commit.message == steps.version.outputs.version && !startsWith(github.ref, 'refs/tags/')
    - run: |
        echo commit message ${{ github.event.head_commit.message }}
        echo version ${{ steps.version.outputs.version }}
        echo bogus ${{ steps.bogus.outputs.bogus }}

    - name: install node
      if: steps.bogus.outputs.bogus != 'true'
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: Cache node dependencies
      if: steps.bogus.outputs.bogus != 'true'
      uses: actions/cache@v2
      env:
        cache-name: cache-dependencies
      with:
        path: |
          ~/.npm
          ~/.pnpm-store
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: install node dependencies
      if: steps.bogus.outputs.bogus != 'true'
      run: pnpm install --ignore-scripts

    - run: pnpm test
      if: steps.bogus.outputs.bogus != 'true'
      env:
        SENTENCECASE: ${{ matrix.sentencecase }}
        CASEPROTECTION: ${{ matrix.caseprotection }}

  release:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v2
      if: startsWith(github.ref, 'refs/tags/')
    - name: install node
      if: startsWith(github.ref, 'refs/tags/')
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: Cache node dependencies
      if: startsWith(github.ref, 'refs/tags/')
      uses: actions/cache@v2
      env:
        cache-name: cache-dependencies
      with:
        path: |
          ~/.npm
          ~/.pnpm-store
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: install node dependencies
      if: startsWith(github.ref, 'refs/tags/')
      run: pnpm install ci --ignore-scripts
    - name: Publish
      if: startsWith(github.ref, 'refs/tags/')
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        access: public
