name: test & publish

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sentencecase: ['on+guess', 'on', 'off']
        caseprotection: [ 'as-needed', 'strict', 'off' ]
        preservequoted: [ '-p', '-P' ]
    steps:
    - uses: actions/checkout@v4
    - run: echo "::version="`jq -r .version package.json` >> $GITHUB_OUTPUT
      id: version
    - name: cancel spurious build on tagged version
      uses: andymckay/cancel-action@master
      if: github.event.head_commit.message == steps.version.outputs.version && !startsWith(github.ref, 'refs/tags/')

    - name: install node
      uses: actions/setup-node@v4
      with:
        node-version: 24.x
        cache: 'npm'

    - run: |
        npm install
        npm run build
        echo ./test/run.js --sc ${{ matrix.sentencecase }} --cp ${{ matrix.caseprotection }} ${{ matrix.preservequoted }} --big
        ./test/run.js --sc ${{ matrix.sentencecase }} --cp ${{ matrix.caseprotection }} ${{ matrix.preservequoted }} --big

  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    needs: test
    if: startsWith(github.ref, 'refs/tags/')
    steps:
    - uses: actions/checkout@v4
    - name: install node
      uses: actions/setup-node@v4
      with:
        node-version: 24.x
        registry-url: 'https://registry.npmjs.org'
    - name: install node dependencies
      run: npm install
    - name: publish
      run: npm publish --provenance --access public
