name: test & publish

on:
  push:
    tags:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sentencecase: [ 'off', 'on', 'on+guess' ]
        caseprotection: [ 'off', 'strict', 'as-needed' ]
    steps:
    - uses: actions/checkout@v2

    - name: install node
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - name: Cache node dependencies
      uses: actions/cache@v2
      env:
        cache-name: cache-dependencies
      with:
        path: |
          ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: install node dependencies
      run: npm ci --ignore-scripts
    - run: npm test
      env:
        SENTENCECASE: ${{ matrix.sentencecase }}
        CASEPROTECTION: ${{ matrix.caseprotection }}

  release:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Publish
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
        npm publish --ignore-scripts
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
