name: test & publish

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sentencecase: ['on+guess', 'on', 'off']
        caseprotection: [ 'as-needed', 'strict', 'off' ]
        preservequoted: [ 'false', 'true' ]
    steps:
    - uses: actions/checkout@v3
    - run: echo "::version="`jq -r .version package.json` >> $GITHUB_OUTPUT
      id: version
    - name: cancel spurious build on tagged version
      uses: andymckay/cancel-action@master
      if: github.event.head_commit.message == steps.version.outputs.version && !startsWith(github.ref, 'refs/tags/')

    - name: install node
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
    - name: Cache node dependencies
      uses: actions/cache@v3
      env:
        cache-name: cache-dependencies
      with:
        path: |
          ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }}

    - run: |
        npm install
        echo '{"sentenceCase": "${{ matrix.sentencecase }}", "caseProtection": "${{ matrix.caseprotection }}", "preserveQuoted": ${{ matrix.preservequoted }}, "big": true}' > test/runtests.json
        npm test -- --color

  release:
    runs-on: ubuntu-latest
    needs: test
    if: startsWith(github.ref, 'refs/tags/')
    steps:
    - uses: actions/checkout@v3
    - name: install node
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
    - name: Cache node dependencies
      uses: actions/cache@v2
      env:
        cache-name: cache-dependencies
      with:
        path: |
          ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }}
    - name: install node dependencies
      run: npm install
    - name: Publish
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        access: public
